// <auto-generated />
using System;
using DB3GP.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DB3GP.Migrations
{
    [DbContext(typeof(DbContainer))]
    [Migration("20220615171927_db349")]
    partial class db349
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DB3GP.DAL.Entities.Archive", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ItemId");

                    b.ToTable("Archive");
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CartQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartID");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Popular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemId = 7000,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 657, DateTimeKind.Local).AddTicks(1929),
                            Image = "637897191887265465.jpg",
                            ItemName = "Laptop HP-1",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "234-156-185",
                            UnitPrice = 20000
                        },
                        new
                        {
                            ItemId = 7001,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6156),
                            Image = "637897191887265465.jpg",
                            ItemName = "Laptop Dell-1",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "True",
                            Quantity = 1,
                            Serial = "555-156-187",
                            UnitPrice = 25000
                        },
                        new
                        {
                            ItemId = 7002,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6613),
                            Image = "637897191887265465.jpg",
                            ItemName = "Laptop Apple-1",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "True",
                            Quantity = 1,
                            Serial = "584-157-189",
                            UnitPrice = 35000
                        },
                        new
                        {
                            ItemId = 7003,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6625),
                            Image = "637897191887265465.jpg",
                            ItemName = "Laptop Lenovo-1",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "128-174-181",
                            UnitPrice = 22000
                        },
                        new
                        {
                            ItemId = 7004,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6629),
                            Image = "637897191887265465.jpg",
                            ItemName = "Laptop Amazon-1",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "987-123-158",
                            UnitPrice = 15000
                        },
                        new
                        {
                            ItemId = 7005,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6632),
                            Image = "637897191887265465.jpg",
                            ItemName = "Laptop HP-2",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "455-789-718",
                            UnitPrice = 40000
                        },
                        new
                        {
                            ItemId = 7006,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6634),
                            Image = "637897202071097364.jpg",
                            ItemName = "LCD-1 Projector",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "557-156-918",
                            UnitPrice = 1000
                        },
                        new
                        {
                            ItemId = 7007,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6636),
                            Image = "637897199425146171.jpg",
                            ItemName = "Data show Screen A-1",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "True",
                            Quantity = 1,
                            Serial = "555-156-168",
                            UnitPrice = 15000
                        },
                        new
                        {
                            ItemId = 7008,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6638),
                            Image = "637897244563427963.jpg",
                            ItemName = "Screen UT-125",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "488-147-187",
                            UnitPrice = 3000
                        },
                        new
                        {
                            ItemId = 7009,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6641),
                            Image = "637897200938565540.jpg",
                            ItemName = "Mouse k-45",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "584-158-582",
                            UnitPrice = 4000
                        },
                        new
                        {
                            ItemId = 7010,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6764),
                            Image = "637897200406465686.jpg",
                            ItemName = "Keyboard rt-45",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "152-434-509",
                            UnitPrice = 2000
                        },
                        new
                        {
                            ItemId = 7011,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6772),
                            Image = "637897244338111378.jpg",
                            ItemName = "Scanner",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "782-314-059",
                            UnitPrice = 3000
                        },
                        new
                        {
                            ItemId = 7012,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6774),
                            Image = "637897201152036805.jpg",
                            ItemName = "Printer",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "384-532-456",
                            UnitPrice = 8000
                        },
                        new
                        {
                            ItemId = 7013,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6776),
                            Image = "637897200712709232.jpg",
                            ItemName = "Michrophone",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "345-735-645",
                            UnitPrice = 7000
                        },
                        new
                        {
                            ItemId = 7014,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6779),
                            Image = "637897191119246922.jpg",
                            ItemName = "Air Condition",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 15,
                            Serial = "534-553-453",
                            UnitPrice = 1000
                        },
                        new
                        {
                            ItemId = 7015,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6780),
                            Image = "637897201590504495.jpg",
                            ItemName = "Processor",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "True",
                            Quantity = 1,
                            Serial = "278-754-467",
                            UnitPrice = 2000
                        },
                        new
                        {
                            ItemId = 7016,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6784),
                            Image = "637897202777982906.jpg",
                            ItemName = "Ram",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "487-754-155",
                            UnitPrice = 1000
                        },
                        new
                        {
                            ItemId = 7017,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6786),
                            Image = "637897198576352429.jpg",
                            ItemName = "CD",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "157-875-556",
                            UnitPrice = 50
                        },
                        new
                        {
                            ItemId = 7018,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6789),
                            Image = "637897244778262668.jpg",
                            ItemName = "Speaker",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "445-787-594",
                            UnitPrice = 500
                        },
                        new
                        {
                            ItemId = 7019,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6791),
                            Image = "637897245239864495.jpg",
                            ItemName = "Table",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "True",
                            Quantity = 10,
                            Serial = "455-887-954",
                            UnitPrice = 500
                        },
                        new
                        {
                            ItemId = 7020,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6793),
                            Image = "637897198856333003.jpg",
                            ItemName = "Chair",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 15,
                            Serial = "457-887-924",
                            UnitPrice = 100
                        },
                        new
                        {
                            ItemId = 7021,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6795),
                            Image = "637897199283252911.jpg",
                            ItemName = "Clock",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 30,
                            Serial = "459-878-948",
                            UnitPrice = 100
                        },
                        new
                        {
                            ItemId = 7022,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6798),
                            Image = "637897199104943091.jpg",
                            ItemName = "Chest",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 5,
                            Serial = "475-877-894",
                            UnitPrice = 400
                        },
                        new
                        {
                            ItemId = 7023,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6800),
                            Image = "637897192735551218.jpg",
                            ItemName = "Cabinet",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 17,
                            Serial = "425-887-994",
                            UnitPrice = 500
                        },
                        new
                        {
                            ItemId = 7024,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6802),
                            Image = "637896963384916375.jpg",
                            ItemName = "Benche",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 20,
                            Serial = "457-887-914",
                            UnitPrice = 1000
                        },
                        new
                        {
                            ItemId = 7025,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6804),
                            Image = "637897199842894480.jpg",
                            ItemName = "Fire extingulisher",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 7,
                            Serial = "405-878-974",
                            UnitPrice = 400
                        },
                        new
                        {
                            ItemId = 7026,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6806),
                            Image = "637897199686917787.jpg",
                            ItemName = "Fan",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 40,
                            Serial = "845-877-914",
                            UnitPrice = 500
                        },
                        new
                        {
                            ItemId = 7027,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6809),
                            Image = "637897202071097364.jpg",
                            ItemName = "Handeld Projector",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "587-156-138",
                            UnitPrice = 1000
                        },
                        new
                        {
                            ItemId = 7028,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6811),
                            Image = "637897202071097364.jpg",
                            ItemName = "CRT Projector",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "579-156-188",
                            UnitPrice = 1000
                        },
                        new
                        {
                            ItemId = 7029,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6813),
                            Image = "637897202071097364.jpg",
                            ItemName = "Laptop Dell-2",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "455-789-178",
                            UnitPrice = 20000
                        },
                        new
                        {
                            ItemId = 7030,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6816),
                            Image = "637897202071097364.jpg",
                            ItemName = "Laptop Apple-2",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "455-789-168",
                            UnitPrice = 20000
                        },
                        new
                        {
                            ItemId = 7031,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6818),
                            Image = "637897202071097364.jpg",
                            ItemName = "Laptop Lenovo-2",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "129-174-818",
                            UnitPrice = 20000
                        },
                        new
                        {
                            ItemId = 7032,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6820),
                            Image = "637897202071097364.jpg",
                            ItemName = "Laptop Amazon-2",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "987-123-518",
                            UnitPrice = 20000
                        },
                        new
                        {
                            ItemId = 7033,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6823),
                            Image = "637897199425146171.jpg",
                            ItemName = "Data show Screen C-123",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "True",
                            Quantity = 1,
                            Serial = "555-156-185",
                            UnitPrice = 15000
                        },
                        new
                        {
                            ItemId = 7034,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6826),
                            Image = "637897199425146171.jpg",
                            ItemName = "Data show Screen D-489",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "True",
                            Quantity = 1,
                            Serial = "555-156-188",
                            UnitPrice = 15000
                        },
                        new
                        {
                            ItemId = 7035,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6829),
                            Image = "637897244563427963.jpg",
                            ItemName = "Screen IE-187",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "482-178-179",
                            UnitPrice = 3000
                        },
                        new
                        {
                            ItemId = 7036,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6831),
                            Image = "637897244563427963.jpg",
                            ItemName = "Screen PE-789",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "487-157-167",
                            UnitPrice = 3000
                        },
                        new
                        {
                            ItemId = 7037,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6833),
                            Image = "637897200938565540.jpg",
                            ItemName = "Mouse GE-48",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "584-158-586",
                            UnitPrice = 4000
                        },
                        new
                        {
                            ItemId = 7038,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6835),
                            Image = "637897200938565540.jpg",
                            ItemName = "Mouse WO-45",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "584-158-858",
                            UnitPrice = 4000
                        },
                        new
                        {
                            ItemId = 7039,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6837),
                            Image = "637897200406465686.jpg",
                            ItemName = "Keyboard e-4",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "162-346-509",
                            UnitPrice = 2000
                        },
                        new
                        {
                            ItemId = 7040,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6839),
                            Image = "637897200406465686.jpg",
                            ItemName = "Keyboard i-7",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 1,
                            Serial = "129-364-509",
                            UnitPrice = 2000
                        },
                        new
                        {
                            ItemId = 7041,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6841),
                            Image = "637897192165684906.jpg",
                            ItemName = "Basket",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 40,
                            Serial = "495-867-964",
                            UnitPrice = 500
                        },
                        new
                        {
                            ItemId = 7042,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6843),
                            Image = "637897192370070754.jpg",
                            ItemName = "Board",
                            ItemStatus = "Free",
                            ItemType = "Furniture",
                            Popular = "False",
                            Quantity = 40,
                            Serial = "495-897-974",
                            UnitPrice = 500
                        },
                        new
                        {
                            ItemId = 7043,
                            DateUpdated = new DateTime(2022, 6, 15, 19, 19, 26, 659, DateTimeKind.Local).AddTicks(6845),
                            Image = "637897195418551957.jpg",
                            ItemName = "Case",
                            ItemStatus = "Free",
                            ItemType = "Electronic Device",
                            Popular = "False",
                            Quantity = 40,
                            Serial = "485-587-924",
                            UnitPrice = 500
                        });
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.Member", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.OwnerShip", b =>
                {
                    b.Property<int>("OwnerShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerShipQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("OwnershipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OwnerShipID");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("OwnerShip");
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.Request", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("RequestQuantity")
                        .HasColumnType("int");

                    b.Property<string>("RequestStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusAfterRestore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakeOrRestore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestID");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.Archive", b =>
                {
                    b.HasOne("DB3GP.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.Cart", b =>
                {
                    b.HasOne("DB3GP.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB3GP.DAL.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.OwnerShip", b =>
                {
                    b.HasOne("DB3GP.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB3GP.DAL.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DB3GP.DAL.Entities.Request", b =>
                {
                    b.HasOne("DB3GP.DAL.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB3GP.DAL.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Item");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
